name: stirred_common_domain
description: common data and domain code for the Stirred project.
version: 1.0.0

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.3
  flutter_secure_storage: ^9.0.0
  retrofit: ^4.0.1
  logger: ^2.0.2
  equatable: ^2.0.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

library:
  entry-points: lib/stirred_common_domain.dart
