name: stirred_common_domain
description: common data and domain code for the Stirred project.
version: 1.0.0

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  logger: ^2.0.2
  equatable: ^2.0.5
  flutter_riverpod: ^2.6.1
  http: ^1.3.0
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3

dev_dependencies:
  lints: ^5.1.1
  test: ^1.21.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.9
  freezed: ^2.4.5
  json_serializable: ^6.7.1

library:
  entry-points: lib/stirred_common_domain.dart
